print("In Python, operators are special symbols that perform operations on variables and values. Here's a basic overview of the types of operators you can use in Python:\n")
print("                                                                                                                                                    ")
print("1. Arithmetic Operators")
print("   Definition: These operators perform basic mathematical operations.")
print("   Operator | Description                     | Example")
print("   ---------|----------------------------------|----------")
print("   +        | Addition                         | 5 + 3")
print("   -        | Subtraction                      | 5 - 3")
print("   *        | Multiplication                   | 5 * 3")
print("   /        | Division                         | 5 / 3")
print("   //       | Floor Division                   | 5 // 3")
print("   %        | Modulus (Remainder)             | 5 % 3")
print("   **       | Exponentiation                   | 5 ** 3\n")
print("                                                                                                                                                    ")
print("2. Comparison Operators")
print("   Definition: These operators compare two values and return a Boolean result (True or False).")
print("   Operator | Description                     | Example")
print("   ---------|----------------------------------|----------")
print("   ==       | Equal to                         | 5 == 3")
print("   !=       | Not equal to                     | 5 != 3")
print("   >        | Greater than                     | 5 > 3")
print("   <        | Less than                        | 5 < 3")
print("   >=       | Greater than or equal to         | 5 >= 3")
print("   <=       | Less than or equal to            | 5 <= 3\n")
print("                                                                                                                                                    ")
print("3. Logical Operators")
print("   Definition: These operators combine conditional statements.")
print("   Operator | Description                     | Example")
print("   ---------|----------------------------------|----------")
print("   and      | Returns True if both statements are true | (5 > 3) and (2 < 4)")
print("   or       | Returns True if at least one statement is true | (5 > 3) or (2 > 4)")
print("   not      | Returns True if the statement is false | not (5 > 3)\n")
print("                                                                                                                                                    ")
print("4. Assignment Operators")
print("   Definition: These operators assign values to variables.")
print("   Operator | Description                     | Example")
print("   ---------|----------------------------------|----------")
print("   =        | Assigns value                   | x = 5")
print("   +=       | Adds and assigns                | x += 3 (same as x = x + 3)")
print("   -=       | Subtracts and assigns           | x -= 3")
print("   *=       | Multiplies and assigns          | x *= 3")
print("   /=       | Divides and assigns             | x /= 3")
print("   //=      | Floor divides and assigns       | x //= 3")
print("   %=       | Modulus and assigns             | x %= 3")
print("   **=      | Exponentiates and assigns       | x **= 3\n")
print("                                                                                                                                                    ")
print("5. Identity Operators")
print("   Definition: These operators compare the memory locations of two objects.")
print("   Operator | Description                     | Example")
print("   ---------|----------------------------------|----------")
print("   is       | Returns True if both variables point to the same object | x is y")
print("   is not   | Returns True if both variables do not point to the same object | x is not y\n")
print("                                                                                                                                                    ")
print("6. Membership Operators")
print("   Definition: These operators test for membership in a sequence (like a list, tuple, or string).")
print("   Operator | Description                     | Example")
print("   ---------|----------------------------------|----------")
print("   in       | Returns True if the value is found in the sequence | 3 in [1, 2, 3]")
print("   not in   | Returns True if the value is not found in the sequence | 5 not in [1, 2, 3]")
