print("                                                                                                                                                    ")
print("3. Logical Operators")
print("   Definition: These operators combine conditional statements.")
print("   Operator | Description                     | Example")
print("   ---------|----------------------------------|----------")
print("   and      | Returns True if both statements are true | (5 > 3) and (2 < 4)")
print("   or       | Returns True if at least one statement is true | (5 > 3) or (2 > 4)")
print("   not      | Returns True if the statement is false | not (5 > 3)\n")
print("                                                                                                                                                    ")